### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by WenTingTseng** [CSLujunyu/Improving-Contextual-Language-Modelsfor-Response-Retrieval-in-Multi-Turn-Conversation#1]
Sorry, i want to ask about how to run it?
Do you have the recipe about it?
thanks a lot for your help

**Comment by CSLujunyu** [comment]
So sorry to reply you late.  

1. First, you need to download the Ubuntu or Douban corpus.

2. Then, you can run the code with the command below.
`python run_classifier_ubuntu_base_ss.py --data_dir /your/data/directory --output_dir /your/data/directory`

3. the suffix of "ss" means speaker sgemenation, and "sp" means sequence pair.

**Comment by CSLujunyu** [comment]
I will update the recipe this weekend.

**Comment by WenTingTseng** [comment]
OK，Thanks a lot
